name: cxr
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy<2
  - matplotlib
  - scikit-image
  - scikit-learn
  - pillow
  - pip
  - pip:
      - albumentations
      - kagglehub
      - timm
      - opencv-python-headless
      - ipykernel
      - jupyter
      - torch==2.3.*
      - tabulate
